string[] serials         # serial numbers to select specific cameras (emtpy string means all cameras)
int64 io_port # io which should be switched (correspond not with the io number in the datacheat of the camera)
bool value
---
string response
